### ISSUE TITLE
Brigde doesn't seem to start until after a restart of vernemq

### ISSUE THREAD

**Issue by larshesel** [erlio/vmq_bridge#2]
Enabling the plugin doesn't establish a connection to the mqtt server we want to establish a bridge to. Only after a restart of vernemq is the connection established.

**Comment by codeadict** [comment]
Is there any plan for this to be fixed @larshesel @dergraf ?

**Comment by larshesel** [comment]
Hi @codeadict , we want to fix this eventually - when I opened the issue I looked at it and IIRC it wasn't trivial to fix. We do want to fix this but it's not super high prio at the moment. That said I'll see if I can find some time this week and take another look and see what effort is required.

**Comment by larshesel** [comment]
I believe this is no longer an issue in the 1.0 release candidates where vmq_bridge has also been included into the vernemq repo.

**Comment by csvisakh7** [comment]
Tried to Implemented vernemq rabbitmq integration based on following link
https://vernemq.com/docs/configuration/bridge.html

configurations done inside vernemq conf file

plugins.vmq_bridge = on
vmq_bridge.tcp.br0 = my rabbitmq url with port
vmq_bridge.tcp.br0.client_id = auto
vmq_bridge.tcp.br0.keepalive_interval = 60
vmq_bridge.tcp.br0.username = rabbitmq username
vmq_bridge.tcp.br0.password = rabbitmq
vmq_bridge.tcp.br0.restart_timeout = 10
vmq_bridge.tcp.br0.try_private = off
vmq_bridge.tcp.br0.topic.1 = /vehicle_details/

'vehicle_details' is the topic in vernemq.
after changing the above configuations,restarted the vernemq service and pushed data to vernemq,but didint get any data in rabbitmq que
 Also manually created a que named 'vehicle_details' in rabbitmq.

what may be the issue ? Is their anything more configuration to do from my side?
